### ISSUE TITLE
Adding module breaks the store

### ISSUE THREAD

**Issue by bennythejudge** [fballiano/docker-magento2#17]
I tried adding a module and after the store is broken. Any page I try to open I get this error:

> An error has happened during application run. See exception log for details. Could not write error message to log. Please use developer mode to see the message.

I looked into the apache container, under `/var/www/html/var/log`, into `exception.log` and I found this recurring entry:

```
[2018-02-19 08:27:56] main.CRITICAL: Can't create directory /var/www/html/generated/code/Magento/Framework/App/Http/. in [Magento\Framework\App\Http\Interceptor] {"exception":"[object] (RuntimeException(code: 0): Can't create directory /var/www/html/generated/code/Magento/Framework/App/Http/. in [Magento\\Framework\\App\\Http\\Interceptor] at /var/www/html/vendor/magento/framework/Code/Generator.php:115)"} []
[2018-02-19 08:27:58] main.CRITICAL: Can't create directory /var/www/html/generated/code/Magento/Framework/App/Http/. in [Magento\Framework\App\Http\Interceptor] {"exception":"[object] (RuntimeException(code: 0): Can't create directory /var/www/html/generated/code/Magento/Framework/App/Http/. in [Magento\\Framework\\App\\Http\\Interceptor] at /var/www/html/vendor/magento/framework/Code/Generator.php:115)"} []
[2018-02-19 08:30:47] main.CRITICAL: Can't create directory /var/www/html/generated/code/Magento/Framework/App/Http/. in [Magento\Framework\App\Http\Interceptor] {"exception":"[object] (RuntimeException(code: 0): Can't create directory /var/www/html/generated/code/Magento/Framework/App/Http/. in [Magento\\Framework\\App\\Http\\Interceptor] at /var/www/html/vendor/magento/framework/Code/Generator.php:115)"} []
```

I installed the module Mageplaza_Smtp by going into the apache container and running the composer:

```
php composer require mageplaza/module-smtp
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
```
I did not change the `docker-compose.yml` file and I download and untarred magento2 with sample data inside a directory `magento2` added at the top of this repo.

Does anyone know what I did wrong or how to fix this problem?

**Comment by nutellinoit** [comment]
did you run composer using the www-data user?

**Comment by bennythejudge** [comment]
No and I did get the warning not to run it as root - and I ignored it.
I will try and report back. 
Thanks.

**Comment by nutellinoit** [comment]
You can use this script as root to fix permissions

```bash
#!/usr/bin/env bash

find . -type f -exec chmod 644 {} \;
echo 'Completed 10%'
find . -type d -exec chmod 755 {} \;
echo 'Completed 20%'
find ./var -type d -exec chmod 777 {} \;
echo 'Completed 30%'
find ./pub/media -type d -exec chmod 777 {} \;
echo 'Completed 40%'
find ./pub/static -type d -exec chmod 777 {} \;
echo 'Completed 50%'
chmod 777 ./app/etc
echo 'Completed 60%'
chmod 644 ./app/etc/*.xml
echo 'Completed 70%'
chown -R www-data:www-data .
echo 'Completed 80%'
chmod u+x bin/magento
echo 'Completed 90%'
chmod u+x fix_permissions.sh
chmod 777 .gitignore
echo 'Completed 100%'


```

**Comment by bennythejudge** [comment]
1) How can I run composer as www-data inside the container? www-data is `no login` and I cannot use su
2) where should I run the script above? inside the apache container?

**Comment by nutellinoit** [comment]
```bash
docker-compose exec --user www-data apache bash
```

You need to create the above script in the root of magento install

**Comment by fballiano** [comment]
@nutellinoit thanks a lot for your help!

@bennythejudge is the issue solved?

**Comment by luanpereira** [comment]
Hi, I need help.
I apply `chwon -R www-data:www-data ./` and `chmod -R 777 ./`, but the problem persists. What are the correct permission settings?

Message error:
`Fatal error: Uncaught RuntimeException: Can't create directory /var/www/html/generated/code/Magento/Framework/App/ResourceConnection/. Class Magento\Framework\App\ResourceConnection\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. in /var/www/html/vendor/magento/framework/Code/Generator.php:135 Stack trace: #0 /var/www/html/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...') #1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...') #2 [internal function]: spl_autoload_call('Magento\\Framewo...') #3 /var/www/html/vendor/magento/framework/Code/Reader/Class in /var/www/html/vendor/magento/framework/Code/Generator.php on line 135`

**Comment by luanpereira** [comment]
Sorry, it was cache, I just to restart the container. However, I would like to know the correct permission settings.

Thanks

**Comment by fballiano** [comment]
Hello everybody, if you run commands within the containers (as root) you've to set the right directory permissions as shown in the magento's documentation: https://devdocs.magento.com/guides/v2.3/config-guide/prod/prod_file-sys-perms.html

otherwise you could  "apt-get install sudo" and then "sudo -su www-data" and run composer or other commands as the "ww-data" user.
