### ISSUE TITLE
Magento 2.3.2 return error SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13

### ISSUE THREAD

**Issue by livioweb** [fballiano/docker-magento2#29]
Warning: Use of undefined constant SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13 - assumed 'SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13' (this will throw an Error in a future version of PHP) in /var/www/html/vendor/magento/framework/Encryption/Encryptor.php on line 153
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.core_config_data' doesn't exist in /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91 Stack trace: #0 /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(91): PDOStatement->execute(Array) #1

**Comment by skapin** [comment]
@livioweb Magento2+ need sodium version > 1.0.13. You have 1.0.11 installed

this is how to install it
https://download.libsodium.org/doc/installation

You can 

1. git clone magento-apache2 iamge of fballiano
2. Modify the Dockerfile to add the procedure ahead
3. Modify the docker-compose to use the new image instead of fbalianno for APACHE service 
4. dont forget to use the same new image for the cron image too, otherwise it will fail

```
FROM php:7.2-apache
MAINTAINER Fabrizio Balliano <fabrizio@fabrizioballiano.com>

RUN apt-get update \
  && apt-get install -y \
    libfreetype6-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng-dev \
    libxslt1-dev \
    tar \
    git \
    vim \
    wget \
    lynx \
    psmisc \
  && apt-get clean

RUN docker-php-ext-configure \
    gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/; \
  docker-php-ext-install \
    gd \
    intl \
    mbstring \
    pdo_mysql \
    xsl \
    zip \
    opcache \
    bcmath \
    soap

RUN wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz && tar xvf libsodium-1.0.18.tar.gz && cd libsodium-1.0.18 && ./configure && make && make check && make install && cd ..
```


Have fun

**Comment by fballiano** [comment]
docker hub had a problem and didn't update the containers correcly. they are updated and fixed now.
