### ISSUE TITLE
production?

### ISSUE THREAD

**Issue by danipolo** [fballiano/docker-magento2#3]
Hi,

I follow this project for a time and really like it. Did you try it in production?

I was wondering to find a good composition with NGINX SSL and REDIS. That's the best I found.

Thanks!

**Comment by fballiano** [comment]
I didn't have the possibility to try it in production :-(

**Comment by danipolo** [comment]
I will try to adapt it for production use.

It would be great to have a good docker-compose enviornment for Magento 2 in production.

Want to help?

**Comment by fballiano** [comment]
What would you like to change?
Most of all I'd like to be sure for it to be able to work on docker 1.2 swarms

**Comment by danipolo** [comment]
We are using [Rancher](http://rancher.com/) for cloud orchestration. Nice UI for production enviornment, monitoring... Also the support of make backups (web data and DB data).

I think the best way to proceed its like the [mageinferno](https://github.com/mageinferno/magento2-docker-compose) project.

The same stack its pretty good, but thinking in the ENV VARIABLES to deploy to production. What do you think?

**Comment by fballiano** [comment]
yes I was thinking you could modify the docker-compose file as you need, that's why I didn't add env variables for everything, there are some (like mysql password etc or varnish memory allocation) things that are internal to the final containers.

if you need some variables feel free to tell me which ones and we can figure it out :)

**Comment by fballiano** [comment]
closing cause of no feedback
